name       : perl-test2-plugin-nowarnings
version    : 0.06
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Test2-Plugin-NoWarnings-0.06.tar.gz : 8288c1d934f69a03224598fbb715adc079c0d1609bfbaea6c88682aab1995800
license    : Artistic-2.0
component  : programming.perl
summary    : Test2::Plugin::NoWarnings - Fail if tests warn
description: |
    Loading this plugin causes your tests to fail if there any warnings while they run. Each warning generates a new failing test and the warning content is outputted via `diag`.
builddeps  :
    - perl-importer
    - perl-ipc-run3
    - perl-sub-info
    - perl-term-table
    - perl-test2-suite
    - perl-test-simple
rundeps    :
    - perl-test-simple
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
